general:
steps:
  mtaBuild:
    buildTarget: 'NEO'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'S0018687056trial_trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
