general:
steps:
  mtaBuild:
    buildTarget: 'CF'
cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 's0018687056trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
